[2025-06-11T12:41:05.067+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-11T12:41:05.098+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nyc_taxi_ml_pipeline.train_linear_model manual__2025-06-11T12:13:31.335012+00:00 [queued]>
[2025-06-11T12:41:05.111+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nyc_taxi_ml_pipeline.train_linear_model manual__2025-06-11T12:13:31.335012+00:00 [queued]>
[2025-06-11T12:41:05.111+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-06-11T12:41:05.125+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): train_linear_model> on 2025-06-11 12:13:31.335012+00:00
[2025-06-11T12:41:05.143+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1049) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-11T12:41:05.145+0000] {standard_task_runner.py:72} INFO - Started process 1058 to run task
[2025-06-11T12:41:05.147+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'nyc_taxi_ml_pipeline', 'train_linear_model', 'manual__2025-06-11T12:13:31.335012+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/dag_full.py', '--cfg-path', '/tmp/tmpj60v0xkj']
[2025-06-11T12:41:05.151+0000] {standard_task_runner.py:105} INFO - Job 15: Subtask train_linear_model
[2025-06-11T12:41:05.212+0000] {task_command.py:467} INFO - Running <TaskInstance: nyc_taxi_ml_pipeline.train_linear_model manual__2025-06-11T12:13:31.335012+00:00 [running]> on host e64a68750d42
[2025-06-11T12:41:05.317+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ml-team' AIRFLOW_CTX_DAG_ID='nyc_taxi_ml_pipeline' AIRFLOW_CTX_TASK_ID='train_linear_model' AIRFLOW_CTX_EXECUTION_DATE='2025-06-11T12:13:31.335012+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-11T12:13:31.335012+00:00'
[2025-06-11T12:41:05.318+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-06-11T12:41:06.203+0000] {logging_mixin.py:190} INFO - Training linear regression model...
[2025-06-11T12:41:06.281+0000] {logging_mixin.py:190} WARNING - 2025/06/11 12:41:06 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-06-11T12:41:30.556+0000] {logging_mixin.py:190} INFO - Model intercept: 23.85
[2025-06-11T12:41:38.468+0000] {logging_mixin.py:190} INFO - Linear regression MLflow run_id: b88ca53da79b434aba69a3756c8da1fe
[2025-06-11T12:41:38.822+0000] {python.py:240} INFO - Done. Returned value was: 23.849501496528802
[2025-06-11T12:41:38.876+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-06-11T12:41:38.876+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=nyc_taxi_ml_pipeline, task_id=train_linear_model, run_id=manual__2025-06-11T12:13:31.335012+00:00, execution_date=20250611T121331, start_date=20250611T124105, end_date=20250611T124138
[2025-06-11T12:41:39.223+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-06-11T12:41:39.253+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-11T12:41:39.254+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
